In [ ]:
%%bigquery
CREATE SCHEMA IF NOT EXISTS weather_dataset
OPTIONS(location="us");

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%bigquery
LOAD DATA OVERWRITE weather_dataset.raw_weather
FROM FILES (
  format = 'CSV',
  uris = ['gs://labs.roitraining.com/data-to-ai-workshop/weather_data.csv'],
  skip_leading_rows = 1
);

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%bigquery
SELECT * FROM weather_dataset.raw_weather LIMIT 5;

Query is running:   0%|          |

Downloading:   0%|          |

,date,city,state,temperature_f,wind_speed_mph,precipitation_in,barometric_pressure_inHg,humidity_percent,weather_condition
0,2025-02-21,Atlanta,GA,55.7,5.0,0.12,29.80,50.4,Cloudy
1,2025-02-26,Atlanta,GA,75.2,10.4,0.03,29.58,49.9,Cloudy
2,2025-03-01,Atlanta,GA,51.7,4.7,0.08,29.74,49.9,Cloudy
3,2025-03-05,Atlanta,GA,74.4,5.1,0.02,29.92,50.4,Cloudy
4,2025-03-10,Atlanta,GA,59.5,9.6,0.09,29.67,57.2,Cloudy

In [ ]:
%%bigquery
CREATE OR REPLACE MODEL weather_dataset.gemini_model
REMOTE WITH CONNECTION `us.gemini_conn`
OPTIONS (ENDPOINT = 'gemini-1.5-flash');

Executing query with job ID: 822462b6-aa2f-4512-bf28-6f0d55cedfb0
Query executing: 0.22s

ERROR:
 404 Not found: Connection gemini_conn; reason: notFound, message: Not found: Connection gemini_conn

Location: US
Job ID: 822462b6-aa2f-4512-bf28-6f0d55cedfb0

In [ ]:
%%bigquery
CREATE OR REPLACE TABLE weather_dataset.weather_with_reports AS
SELECT
  *,
  ml_generate_text_result AS weather_report
FROM
  ML.GENERATE_TEXT(
    MODEL `weather_dataset.gemini_model`,
    (
      SELECT
        *,
        CONCAT(
          'Based on a temperature of ', temperature,
          ' degrees, wind speed of ', wind_speed,
          ' mph, and humidity of ', humidity,
          '%, write a short, professional weather warning or report.'
        ) AS prompt
      FROM
        `weather_dataset.raw_weather`
    ),
    STRUCT(
      0.2 AS temperature,
      250 AS max_output_tokens
    )
  );

Executing query with job ID: de05a82f-bb4e-4f98-bf82-4f033734751f
Query executing: 0.39s

ERROR:
 404 Not found: Model qwiklabs-gcp-01-bb0d31ab0812:weather_dataset.gemini_model; reason: notFound, message: Not found: Model qwiklabs-gcp-01-bb0d31ab0812:weather_dataset.gemini_model

Location: US
Job ID: de05a82f-bb4e-4f98-bf82-4f033734751f

In [ ]:
%%bigquery
CREATE OR REPLACE MODEL weather_dataset.gemini_model
REMOTE WITH CONNECTION `us.gemini_conn`
OPTIONS (ENDPOINT = 'gemini-1.5-flash-002');

Executing query with job ID: 8203b026-7386-425e-9a3e-593b4d40d697
Query executing: 0.64s

ERROR:
 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/qwiklabs-gcp-01-bb0d31ab0812/queries/8203b026-7386-425e-9a3e-593b4d40d697?maxResults=0&location=US&prettyPrint=false: Not found: Publisher Model `projects/qwiklabs-gcp-01-bb0d31ab0812/locations/us-central1/publishers/google/models/gemini-1.5-flash-002` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions

Location: US
Job ID: 8203b026-7386-425e-9a3e-593b4d40d697

In [ ]:
%%bigquery
CREATE OR REPLACE MODEL weather_dataset.gemini_model
REMOTE WITH CONNECTION `us.gemini_conn`
OPTIONS (ENDPOINT = 'gemini-1.0-pro');

Executing query with job ID: 5be42371-ef7d-4e08-8841-3c09c6e09ee1
Query executing: 0.56s

ERROR:
 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/qwiklabs-gcp-01-bb0d31ab0812/queries/5be42371-ef7d-4e08-8841-3c09c6e09ee1?maxResults=0&location=US&prettyPrint=false: Not found: Publisher Model `projects/qwiklabs-gcp-01-bb0d31ab0812/locations/us-central1/publishers/google/models/gemini-1.0-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions

Location: US
Job ID: 5be42371-ef7d-4e08-8841-3c09c6e09ee1

In [ ]:
!gcloud services enable aiplatform.googleapis.com

In [ ]:
!bq mk --connection --location=US --project_id=qwiklabs-gcp-01-bb0d31ab0812 --connection_type=CLOUD_RESOURCE gemini_conn

BigQuery error in mk operation: Already Exists: Connection
projects/571122703372/locations/us/connections/gemini_conn

In [ ]:
%%bigquery
CREATE OR REPLACE MODEL weather_dataset.gemini_model
REMOTE WITH CONNECTION `us.gemini_conn`
OPTIONS (ENDPOINT = 'gemini-pro');

Executing query with job ID: e0900c5f-a190-44e4-b6ee-5d6daf4e4f93
Query executing: 0.56s

ERROR:
 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/qwiklabs-gcp-01-bb0d31ab0812/queries/e0900c5f-a190-44e4-b6ee-5d6daf4e4f93?maxResults=0&location=US&prettyPrint=false: Not found: Publisher Model `projects/qwiklabs-gcp-01-bb0d31ab0812/locations/us-central1/publishers/google/models/gemini-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions

Location: US
Job ID: e0900c5f-a190-44e4-b6ee-5d6daf4e4f93

In [ ]:
%%bigquery
CREATE OR REPLACE MODEL weather_dataset.gemini_model
REMOTE WITH CONNECTION `us.gemini_conn`
OPTIONS (ENDPOINT = 'gemini-2.0-flash');

Executing query with job ID: 3a9efda4-40f1-4cd2-b0c6-9d4659c93a23
Query executing: 0.61s

ERROR:
 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/qwiklabs-gcp-01-bb0d31ab0812/queries/3a9efda4-40f1-4cd2-b0c6-9d4659c93a23?maxResults=0&location=US&prettyPrint=false: Not found: Publisher Model `projects/qwiklabs-gcp-01-bb0d31ab0812/locations/us-central1/publishers/google/models/gemini-2.0-flash` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions

Location: US
Job ID: 3a9efda4-40f1-4cd2-b0c6-9d4659c93a23

In [ ]:
!gcloud services enable aiplatform.googleapis.com

In [ ]:
%%bigquery
CREATE OR REPLACE MODEL weather_dataset.gemini_model
REMOTE WITH CONNECTION `us.gemini_conn`
OPTIONS (ENDPOINT = 'gemini-1.5-pro');

Executing query with job ID: 42870ace-dfcc-43c0-9b78-bac14fc417a2
Query executing: 0.55s

ERROR:
 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/qwiklabs-gcp-01-bb0d31ab0812/queries/42870ace-dfcc-43c0-9b78-bac14fc417a2?maxResults=0&location=US&prettyPrint=false: Not found: Publisher Model `projects/qwiklabs-gcp-01-bb0d31ab0812/locations/us-central1/publishers/google/models/gemini-1.5-pro` was not found or your project does not have access to it. Please ensure you are using a valid model version. For more information, see: https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versions

Location: US
Job ID: 42870ace-dfcc-43c0-9b78-bac14fc417a2

In [ ]:
%%bigquery
CREATE OR REPLACE MODEL weather_dataset.gemini_model
REMOTE WITH CONNECTION DEFAULT
OPTIONS(ENDPOINT = 'gemini-2.5-flash');

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%bigquery
CREATE OR REPLACE TABLE weather_dataset.weather_with_reports AS
SELECT
  *,
  ml_generate_text_result AS weather_report
FROM
  ML.GENERATE_TEXT(
    MODEL `weather_dataset.gemini_model`,
    (
      SELECT
        *,
        CONCAT(
          'Based on a temperature of ', temperature_f,
          ' degrees, wind speed of ', wind_speed_mph,
          ' mph, and humidity of ', humidity_percent,
          '%, write a short, professional weather warning or report.'
        ) AS prompt
      FROM
        `weather_dataset.raw_weather`
    ),
    STRUCT(
      0.2 AS temperature,
      250 AS max_output_tokens
    )
  );

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [ ]:
%%bigquery
select * from weather_dataset.weather_with_reports

Query is running:   0%|          |

Downloading:   0%|          |

,ml_generate_text_result,ml_generate_text_status,date,city,state,temperature_f,wind_speed_mph,precipitation_in,barometric_pressure_inHg,humidity_percent,weather_condition,prompt,weather_report
0,"{""candidates"":[{""avg_logprobs"":-0.201156593504...",,2025-03-18,Atlanta,GA,91.0,4.0,0.01,29.91,39.4,Sunny,"Based on a temperature of 91 degrees, wind spe...","{""candidates"":[{""avg_logprobs"":-0.201156593504..."
1,"{""candidates"":[{""avg_logprobs"":-0.226301509023...",,2025-02-28,Atlanta,GA,70.0,3.0,0.02,30.17,39.7,Sunny,"Based on a temperature of 70 degrees, wind spe...","{""candidates"":[{""avg_logprobs"":-0.226301509023..."
2,"{""candidates"":[{""avg_logprobs"":-0.211407319093...",,2025-03-09,Atlanta,GA,76.0,0.3,0.03,30.09,35.1,Sunny,"Based on a temperature of 76 degrees, wind spe...","{""candidates"":[{""avg_logprobs"":-0.211407319093..."
3,"{""candidates"":[{""avg_logprobs"":-0.188004634840...",,2025-02-20,Atlanta,GA,93.0,5.3,0.01,30.16,23.3,Sunny,"Based on a temperature of 93 degrees, wind spe...","{""candidates"":[{""avg_logprobs"":-0.188004634840..."
4,"{""candidates"":[{""avg_logprobs"":-0.147524150449...",,2025-03-06,Atlanta,GA,65.8,6.2,1.38,29.79,64.0,Rainy,"Based on a temperature of 65.8 degrees, wind s...","{""candidates"":[{""avg_logprobs"":-0.147524150449..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,"{""candidates"":[{""avg_logprobs"":-0.175609268188...",,2025-02-18,Seattle,WA,33.1,25.9,2.32,29.02,95.8,Stormy,"Based on a temperature of 33.1 degrees, wind s...","{""candidates"":[{""avg_logprobs"":-0.175609268188..."
296,"{""candidates"":[{""avg_logprobs"":-0.156547225952...",,2025-02-23,Seattle,WA,37.6,27.2,2.44,28.87,90.1,Stormy,"Based on a temperature of 37.6 degrees, wind s...","{""candidates"":[{""avg_logprobs"":-0.156547225952..."
297,"{""candidates"":[{""avg_logprobs"":-0.157868164062...",,2025-03-16,Seattle,WA,43.3,48.8,3.36,28.93,90.1,Stormy,"Based on a temperature of 43.3 degrees, wind s...","{""candidates"":[{""avg_logprobs"":-0.157868164062..."
298,"{""candidates"":[{""avg_logprobs"":-0.179717942288...",,2025-03-05,Seattle,WA,50.4,11.3,0.17,29.52,46.6,Cloudy,"Based on a temperature of 50.4 degrees, wind s...","{""candidates"":[{""avg_logprobs"":-0.179717942288..."
299,"{""candidates"":[{""avg_logprobs"":-0.230727953788...",,2025-02-25,Seattle,WA,36.8,14.8,0.88,29.59,72.2,Snowy,"Based on a temperature of 36.8 degrees, wind s...","{""candidates"":[{""avg_logprobs"":-0.230727953788..."